stages:
    - compilation

build_linux_arm64:
    stage: compilation
    image: golang:1.9
    script: 
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags='-s -w'
      - mkdir groups
      - mkdir data
    artifacts:
      - galene
      - static
      - data
      - groups

